### ISSUE TITLE
aiopg.sa.Engine doesn't implement sqlalchemy.engine.base.Engine

### ISSUE THREAD

**Issue by nucular** [aio-libs/aiopg#123]
Hi,
It appears to me that the `Engine` class is far from implementing the current interface of `sqlalchemy.engine.base.Engine`. Same is true for `SAConnection`. This causes many duck-typed SQLAlchemy functions to fail.

For example:
```py
import asyncio
from sqlalchemy import Table, MetaData, Column, Integer
from aiopg.sa import create_engine

metadata = MetaData()
Test = Table("Test", metadata,
  Column("test", Integer)
)

async def run():
  engine = create_engine(
    database="postgres",
    user="postgres",
    password="- snip -",
    host="localhost",
    port="5432"
  )

  metadata.create_all(engine)

if __name__ == "__main__":
  loop = asyncio.get_event_loop()
  loop.run_until_complete(run())
```
results in
```py
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    loop.run_until_complete(run())
  File "C:\tools\python\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\tools\python\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\tools\python\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 20, in run
    metadata.create_all(engine)
  File "C:\tools\python\lib\site-packages\sqlalchemy\sql\schema.py", line 3742, in create_all
    bind._run_visitor(ddl.SchemaGenerator,
AttributeError: '_PoolContextManager' object has no attribute '_run_visitor'
```

due to the`_run_visitor` method missing in `Engine`. Why are these classes not subclassing SQLAlchemy's `Engine` or `Connectable`?

**Comment by asvetlov** [comment]
Because they are have different signatures. Making function a coroutine changes a lot.

For your particular case `metadata.create_all()` tries to execute SQL code inside.
That means it should be a coroutine but it isn't. In turn `_run_visitor` should be a coroutine also.

That's why `aiopg` doesn't support `metadata.create_all`. It's just impossible. Sorry for that.

**Comment by mpaolini** [comment]
you can use the `loop.run_in_executor` utility to safely run synchronous code in a coroutine without blocking the loop

```python
import asyncio
import logging

import sqlalchemy as sa
import aiopg

logger = logging.getLogger()

CONN_STRING = 'postgresql://test:test@127.0.0.1/aiopg_test'

async def main(loop):
    metadata = sa.MetaData()
    Test = sa.Table("Test", metadata, sa.Column("test", sa.Integer))
    engine = sa.create_engine(CONN_STRING)
    await loop.run_in_executor(None, metadata.create_all, engine)
    async with aiopg.create_pool(CONN_STRING) as pool:
        async with pool.acquire() as conn:
            async with conn.cursor() as curs:
                await curs.execute(
                    str(Test.insert().compile(dialect=sa.dialects.postgresql.dialect())),
                    {'test': 1}
                )

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
```

**Comment by asvetlov** [comment]
It works but it's an opened can of worms.

I believe sharing the same metadata between sync and async code is **very** bad idea.
Especially taking into account the fact that metadata will be **bound** with SqlAlchemy's engine by `.create_all()` call.
In practice that means all subqueries and other things which was forbidden for *unbound* metadata becomes available, but they are **synchronous**.

Instead of raising an error (maybe non clear with cryptic message and context but it's better than nothing) async calls may execute sync SQL queries implicitly without any warning!!!

If you are ok with sync access to database (it may be a good option it DB server is physically executed on the same machine as application code and queries are fast) -- just use standard old good  sqlalchemy without aiopg at all!

If you are really need async DB queries -- don't mix them with ability to **implicitly** execute any query on demand (for calculating default value for example, getting next sequence number or analyzing db schema and so on).
