### ISSUE TITLE
What is the recommanded usage for aiopg ?

### ISSUE THREAD

**Issue by ikit** [aio-libs/aiopg#282]
Hi, 

In your examples, all is done in a same function : creation of the pool > connexion > cursor, and then execution of the query. What is the best to do in the case of a real web application : shall I create a new pool/connexion/cursor each time I need to use the database ? or is it better to create one pool that will be used by the whole application ?

**Comment by popravich** [comment]
Hi, @ikit 
Check out this demo app https://github.com/KeepSafe/aiohttp/tree/master/demos/polls/aiohttpdemo_polls.
Basically, you should keep connections (pool) to db for a whole application lifetime and using them in hander functions.
Otherwise you'll be adding too much latency on every request to establish connection to database.

**Comment by ikit** [comment]
Thanks :)
