### ISSUE TITLE
How to make concurrent queries to a database?

### ISSUE THREAD

**Issue by panagiks** [aio-libs/aiopg#356]
I'm probably missing sth really obvious .. I'm trying to make a few concurrent queries to a database in the following form:

```py
with (yield from request.app['pg_engine']) as conn:
    tasks = []
    tasks.append(conn.execute(tbl.insert().values(a=1,b=2....)
    tasks.append(conn.execute(other_tbl.insert().values(a=2,b=3....)
    res = yield from asyncio.gather(*tasks)
```
but I get : `RuntimeError: cursor.execute() called while another coroutine is already waiting for incoming data`.

So I guess my approach is not the best practice. My questions is how should/would I make a few concurrent queries to create rows in a few different tables?

Note:  `app['pg_engine']` is created using `aiopg.sa.create_engine`

**Comment by jettify** [comment]
You are correct, you need to execute each query in separate connection. 
```
        async with engine.acquire() as conn:
            await conn.execute(tbl.insert().values(val='abc'))
```

**Comment by jettify** [comment]
closing for now, feel free to open new issue

**Comment by shish** [comment]
Does this mean that it's impossible to have concurrent queries inside a transaction?

(Necromancing because this is the top google result for `cursor.execute() called while another coroutine is already waiting for incoming data`, which is the error message that appears when you attempt to put concurrent queries in a transaction)

**Comment by vir-mir** [comment]
@shish  hi.
if I understand your question correctly, yes `Two cursors can’t execute concurrent queries on the same asynchronous connection.` the details [here](http://initd.org/psycopg/docs/advanced.html#asynchronous-support).
But, if you write an example. We may be able to give a more detailed answer.

**Comment by shish** [comment]
Not sure how to summarise in code, but I'm porting a traditional webapp (start transaction at the start of the request, do a bunch of queries inside that transaction, `commit` if we return HTTP 20X/30X or `rollback` if we return HTTP 40X/50X) into the async world.

I was hoping to get some speedups by replacing eg
```
comments = []
for cid in post.comment_ids:
    comments.append(fetch_comment(cid))
```
with
```
comments = await asyncio.gather(*[async_fetch_comment(cid) for cid in post.comment_ids])
```

It looks like a direct 1:1 translation of the old code won't work, but since the read and write codepaths are pretty distinct, it should be possible to have read-only code go via a connection pool, and read-write code go via a single dedicated sequential-query-inside-transaction connection...

**Comment by vir-mir** [comment]
@shish No, in each "async_fetch_comment" you need to use their own connection of pool, you will get a benefit, in that the connection are reused, that is, they are released and not closed.
You can also open the connection at the beginning, and then they will be re-used  https://aiopg.readthedocs.io/en/stable/sa.html#engine  the argument `minsize` is responsible for the number of open connections at the time the pool is created`

**Comment by fabiocerqueira** [comment]
@shish Hey, sorry for the late ping. Could you let me know if you got it sorted?

**Comment by shish** [comment]
I don't actually remember, but looking at the code that I was working on four years ago, I don't see any sign of parallel queries happening :(

**Comment by fabiocerqueira** [comment]
Thank you for your time. I'll try to have a deeper look and put it on this thread if I find something
